export interface CPUPreformat {
    "Core Count": string,
    "Core Family": string,
    "ECC Support": string,
    "Includes CPU Cooler": string,
    "Includes Cooler": string,
    "Integrated Graphics": string,
    "L2 Cache": string,
    "L3 Cache": string,
    Lithography: string,
    Manufacturer: string,
    "Maximum Supported Memory": string,
    Microarchitecture: string,
    Packaging: string,
    "Part #": string,
    "Performance Core Boost Clock": string,
    "Performance Core Clock": string,
    Series: string,
    "Simultaneous Multithreading": string,
    Socket: string,
    TDP: string,
    "Thread Count": string,
    name: string,
    partType: "CPU"
}

export interface MotherboardPreformat {
    Chipset: string,
    Color: string,
    "Form Factor": string,
    "Half Mini-PCIe Slots": string,
    "M.2 Slots": string,
    Manufacturer: string,
    "Memory Max": string,
    "Memory Slots": string,
    "Memory Speed": string,
    "Memory Type": string,
    "Mini-PCIe / mSATA Slots": string,
    "Mini-PCIe Slots": string,
    "Onboard Ethernet": string,
    "Onboard Video": string,
    "PCI Slots": string,
    "PCIe x1 Slots": string,
    "PCIe x16 Slots": string,
    "PCIe x4 Slots": string,
    "PCIe x8 Slots": string,
    "Part #": string,
    "RAID Support": string,
    "SATA 6.0 Gb/s": string,
    "Socket / CPU": string,
    "Supports ECC": string,
    "USB 2.0 Headers": string,
    "USB 2.0 Headers (Single Port)": string,
    "USB 3.2 Gen 1 Headers": string,
    "USB 3.2 Gen 2 Headers": string,
    "USB 3.2 Gen 2x2 Headers": string,
    "Uses Back-Connect Connectors": string,
    "Wireless Networking": string,
    "mSATA Slots": string,
    name: string,
    partType: "Motherboard",
}

export interface MemoryPreformat {
    "CAS Latency": string,
    Color: string,
    "ECC / Registered": string,
    "First Word Latency": string,
    "Form Factor": string,
    "Heat Spreader": string,
    Manufacturer: string,
    Modules: string,
    "Part #": string,
    "Price / GB": string,
    Speed: string,
    Timing: string,
    Voltage: string,
    name: string,
    partType: "Memory",
}

export interface CasePreformat {
    Color: string,                                                                                                                                                
    Dimensions: string,                                                                                     
    "Drive Bays": string,                                                                                            
    "Expansion Slots": string,                                                                                      
    "Front Panel USB": string,
    Manufacturer: string,
    "Maximum Video Card Length": string,
    "Motherboard Form Factor": string,
    "Part #": string,
    "Power Supply": string,
    "Power Supply Shroud": string,
    "Side Panel": string,
    Type: string,
    Volume: string,
    name: string,
    partType: string,
}

export type Preformat = CPUPreformat | MemoryPreformat | MotherboardPreformat | CasePreformat